// ==========================================================
// GENERATED by gen_flavors.py from flavors.yaml — DO NOT EDIT.
// Add/change flavors in flavors.yaml and regenerate instead.
// ==========================================================

#ifndef __PS3_GAMEDIR_DEFS_H
#define __PS3_GAMEDIR_DEFS_H

#if defined(STANDALONETA)
#  define PS3_GAMEDIR       "missionpack"
#  define PS3_LOG_SUFFIX    "log_ta.txt"
#  define PS3_TITLE         "teamarena-PS3"
#elif defined(STANDALONEOA)
#  define PS3_GAMEDIR       "baseoa"
#  define PS3_LOG_SUFFIX    "log_oa.txt"
#  define PS3_TITLE         "openarena-PS3"
#elif defined(ELITEFORCE)
#  define PS3_GAMEDIR       "baseEF"
#  define PS3_LOG_SUFFIX    "log_ef.txt"
#  define PS3_TITLE         "eliteforce-PS3"
#elif defined(STANDALONEQ3F)
#  define PS3_GAMEDIR       "q3f2"
#  define PS3_LOG_SUFFIX    "log_q3f.txt"
#  define PS3_TITLE         "q3f-PS3"
#else
#  define PS3_GAMEDIR       "baseq3"
#  define PS3_LOG_SUFFIX    "log.txt"
#  define PS3_TITLE         "ioquake3-PS3"
#endif

#endif // __PS3_GAMEDIR_DEFS_H
